// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtipzrzcdudnqznqcoiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0aXB6cnpjZHVkbnF6bnFjb2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3OTYxMzYsImV4cCI6MjA2NDM3MjEzNn0.evN_NZq-nHG40Mirqe48HwtiNDX4-uumiu1SUhOLemg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);